### ISSUE TITLE
Arrow alignment is broken after `@rc-component/trigger` update

### ISSUE THREAD

**Issue by FlorisVeldhuizen** [react-component/tooltip#441]
In the _provided_ example of this repo, the tooltip arrow now aligns like this:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/10500846/218737019-76f72e60-a7fa-41ca-a0f5-419f67691a5b.png">

which is caused by this styling that is applied to `<div class="rc-tooltip-arrow"></div>`.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/10500846/218737304-85ecf6d8-3a06-441a-a602-d07092c290c8.png">

When this is removed, the styling looks good again:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/10500846/218737602-9f4b3580-d311-4ba1-be75-0dded83dc6f4.png">
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/10500846/218738018-0a8d7d91-fda8-480d-8e3b-f80dc563e6f4.png">

Changes in the `@rc-component/trigger` have caused changes in the arrow alignment, so the problem probably lies there.

**Comment by ilinalexgit** [comment]
Have the same issue, it looks like `arrowContent` prop is ignored.

**Comment by psiclopz** [comment]
Same issue.  The "arrowContent" prop still exists on Tooltip, but was removed from Popup, and the instance of Popup in the Tooltip was changed to omit the arrowContent prop in the 5.3.1->6.0.0 changes.
https://github.com/react-component/tooltip/compare/v5.3.1...v6.0.0
Popup.tsx line 9
Tooltip.tsx line 76

**Comment by zombieJ** [comment]
In latest version. `rc-tooltip` use `@rc-component/trigger` arrow config instead. But yes, ignore arrowContent should be fixed.

**Comment by cristian-sima** [comment]
So in the end, which is the solution? I am still having the arrow in wrong position: 
![image](https://github.com/react-component/tooltip/assets/12199042/70383402-3499-4017-b3e9-f811ca668d6a)

**Comment by FlorisVeldhuizen** [comment]
> So in the end, which is the solution? I am still having the arrow in wrong position: ![image](https://user-images.githubusercontent.com/12199042/258458223-70383402-3499-4017-b3e9-f811ca668d6a.png)

The issue still persists, I don't know why this was closed!

**Comment by yoyo837** [comment]
> > So in the end, which is the solution? I am still having the arrow in wrong position: ![image](https://user-images.githubusercontent.com/12199042/258458223-70383402-3499-4017-b3e9-f811ca668d6a.png)
> 
> The issue still persists, I don't know why this was closed!

Run `npm ls @rc-component/trigger` to see what version it is.

**Comment by k10wl** [comment]
> > > So in the end, which is the solution? I am still having the arrow in wrong position: ![image](https://user-images.githubusercontent.com/12199042/258458223-70383402-3499-4017-b3e9-f811ca668d6a.png)
> > 
> > 
> > The issue still persists, I don't know why this was closed!
> 
> Run `npm ls @rc-component/trigger` to see what version it is.

same issue, result of ls - @rc-component/trigger@1.17.0

**Comment by FlorisVeldhuizen** [comment]
The [example page](https://react-component.github.io/tooltip/examples) is broken, so no easy way to show you atm. If you are able to fix the example page you will see that the arrows still not align properly!

**Comment by yoyo837** [comment]
Try this page https://react-component.github.io/tooltip/demo/

ref: https://github.com/react-component/tooltip/pull/460

**Comment by FlorisVeldhuizen** [comment]
Thanks for providing the working demo page!
The arrow alignment:

![image](https://github.com/react-component/tooltip/assets/10500846/cc5b8cf9-9285-47aa-9efe-00daf56e9218)

**Comment by yoyo837** [comment]
@zombieJ  Do we need to set the trigger's transform-origin in the tooltip to solve it?
