### ISSUE TITLE
Arrow alignment on `placement` other than `top` is broken

### ISSUE THREAD

**Issue by xsjcTony** [react-component/tooltip#445]
@zombieJ Hey, really sorry for bothering but I'm comping up with another bug.

Simply arrow alignment on `placement` other than `top` seems all broken.

Here's a reproduction for `top` / `left` / `right` / and `bottom`, you can have a look, appreciate it.

https://stackblitz.com/edit/vitejs-vite-8228fq?file=src/App.tsx

![image](https://user-images.githubusercontent.com/45784210/225460287-11d53fdf-c5af-47de-a0ce-4d43c109fa52.png)

**Comment by zombieJ** [comment]
Seems it can just be fixed with style: https://stackblitz.com/edit/vitejs-vite-drjjx5?file=src%2Fassets%2Fstyles%2Frc-tooltip.scss

**Comment by xsjcTony** [comment]
@zombieJ Yeah I agree with you, but I think the original style provided with the package is still broken: https://stackblitz.com/edit/vitejs-vite-8228fq?file=src/App.tsx
But anyway, it's trivial.
